from pydantic import BaseModel
from typing import List, Dict, Any

class IngredientCreate(BaseModel):
    name: str
    quantity: float
    unit: str
    is_staple: bool = False
# ajouter la date de péremption

# What the server returns (along with the ID generated by the database)
class Ingredient(IngredientCreate):
    id: int
    is_in_shopping_list: bool

    class Config:
        from_attributes = True # Converts SQLAlchemy objects to JSON

class EquipmentBase(BaseModel):
    name: str
    is_active: bool = True

class EquipmentCreate(EquipmentBase):
    pass

class Equipment(EquipmentBase):
    id: int
    class Config:
        from_attributes = True

class FavoriteRecipeCreate(BaseModel):
    title: str
    details: Dict[str, Any]

class FavoriteRecipe(BaseModel):
    id: int
    title: str
    details: Dict[str, Any]

    class Config:
        from_attributes = True