from pydantic import BaseModel
from typing import Optional

class IngredientCreate(BaseModel):
    name: str
    quantity: float
    unit: str
    is_staple: bool = False
# ajouter la date de péremption

# What the server returns (along with the ID generated by the database)
class Ingredient(IngredientCreate):
    id: int
    is_in_shopping_list: bool

    class Config:
        from_attributes = True # Converts SQLAlchemy objects to JSON